const express = require('express');
const { PrismaClient } = require('@prisma/client');
const voiceService = require('../services/voiceService');
const { uploadFile } = require('../services/storage');

const router = express.Router();
const prisma = new PrismaClient();

// POST /api/blessing/save
router.post('/save', async (req, res) => {
  try {
    // No gating: everyone can save blessings.

    const { lovedOneId, title, transcript, audioUrl, text } = req.body;
    const bodyText = transcript ?? text;

    if (!title || !bodyText) {
      return res.status(400).json({ error: 'title and transcript (or text) are required' });
    }

    let resolvedLovedOne = null;
    if (lovedOneId) {
      resolvedLovedOne = await prisma.lovedOne.findFirst({
        where: { id: lovedOneId, userId: req.user.id },
      });
      if (!resolvedLovedOne) {
        return res.status(404).json({ error: 'Loved one not found' });
      }
    }

    let finalAudioUrl = audioUrl;
    if (!finalAudioUrl && resolvedLovedOne?.voiceId) {
      const buf = await voiceService.synthesize(bodyText, resolvedLovedOne.voiceId);
      const fileName = `blessings/${req.user.id}/${Date.now()}.mp3`;
      finalAudioUrl = await uploadFile(buf, fileName, 'audio/mpeg');
    }

    if (!finalAudioUrl) {
      return res.status(400).json({ error: 'audioUrl is required, or lovedOneId with a cloned voice' });
    }

    const blessing = await prisma.blessing.create({
      data: {
        userId: req.user.id,
        lovedOneId: lovedOneId || null,
        title,
        transcript: bodyText,
        audioUrl: finalAudioUrl,
      },
    });

    return res.status(201).json({ blessing });
  } catch (err) {
    console.error('Save blessing error:', err);
    return res.status(500).json({ error: 'Failed to save blessing', message: err.message });
  }
});

// GET /api/blessing/list
router.get('/list', async (req, res) => {
  try {
    // No gating: everyone can list blessings.

    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 20;
    const skip = (page - 1) * limit;

    const [blessings, total] = await Promise.all([
      prisma.blessing.findMany({
        where: { userId: req.user.id },
        orderBy: { createdAt: 'desc' },
        skip,
        take: limit,
        include: { lovedOne: { select: { id: true, name: true } } },
      }),
      prisma.blessing.count({
        where: { userId: req.user.id },
      }),
    ]);

    const shaped = blessings.map((b) => ({
      ...b,
      lovedOneName: b.lovedOne?.name,
    }));

    return res.json({
      blessings: shaped,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
        hasNext: page * limit < total,
        hasPrev: page > 1,
      },
    });
  } catch (err) {
    console.error('List blessings error:', err);
    return res.status(500).json({ error: 'Failed to fetch blessings', message: err.message });
  }
});

// GET /api/blessing/:id/export — returns audio + disclosure metadata (MVP)
router.get('/:id/export', async (req, res) => {
  try {
    // No gating: everyone can export.

    const blessing = await prisma.blessing.findFirst({
      where: { id: req.params.id, userId: req.user.id },
    });

    if (!blessing) {
      return res.status(404).json({ error: 'Blessing not found' });
    }

    return res.json({
      audioUrl: blessing.audioUrl,
      disclaimer:
        'This file is AI-generated by Swara. A full embedded audio watermark pipeline may be added in a future release; do not treat as raw human recording.',
      metadata: {
        title: blessing.title,
        aiGeneratedBy: 'Swara',
        transcriptPreview: blessing.transcript?.slice(0, 200),
      },
    });
  } catch (err) {
    console.error('Blessing export error:', err);
    return res.status(500).json({ error: 'Export failed', message: err.message });
  }
});

module.exports = router;
